# Generated by Django 4.1.7 on 2023-03-12 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colorCode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('discount', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.deal_image)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('discount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('discount', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.offer_image)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=350, null=True)),
                ('feature1', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('feature2', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('feature3', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('feature4', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('feature5', models.CharField(blank=True, default='lorem ipsum lorem ipsum lorem ipsum lorem ipsum', max_length=250, null=True)),
                ('onSale', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=product.models.product_image)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=350, null=True)),
                ('itemNumber', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=product.models.product_variation_image)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=product.models.product_variation_image)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=product.models.product_variation_image)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=product.models.product_variation_image)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=product.models.product_variation_image)),
                ('price', models.PositiveIntegerField()),
                ('discountPrice', models.PositiveIntegerField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=10)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productVariations', to='product.product')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.subcategory_image)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorySizes', to='product.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(default=3)),
                ('review', models.CharField(default='Nice product', max_length=80)),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='product.productvariation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productvariation',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryProducts', to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.deal'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.offer'),
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategoryroducts', to='product.subcategory'),
        ),
    ]
